/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a;

import javax.swing.JOptionPane;

/**
 *
 * @author 2830482411018
 */
public class radioButton extends javax.swing.JFrame {

    /**
     * Creates new form radioButton
     */
    String sexo;
    boolean tecnologia, astronomia, esportes;
    public radioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGrupo = new javax.swing.ButtonGroup();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        rdoMasculino = new javax.swing.JRadioButton();
        rdoFeminino = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chkTecnologia = new javax.swing.JCheckBox();
        chkAstronomia = new javax.swing.JCheckBox();
        chkEsportes = new javax.swing.JCheckBox();
        lblIdioma = new javax.swing.JLabel();
        cbbIdiomas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblSexo.setText("Sexo");

        btgGrupo.add(rdoMasculino);
        rdoMasculino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdoMasculino.setText("Masculino");

        btgGrupo.add(rdoFeminino);
        rdoFeminino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdoFeminino.setText("Feminino");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Interesses");

        chkTecnologia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkTecnologia.setText("Tecnologia");
        chkTecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTecnologiaActionPerformed(evt);
            }
        });

        chkAstronomia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkAstronomia.setText("Astronomia");
        chkAstronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAstronomiaActionPerformed(evt);
            }
        });

        chkEsportes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkEsportes.setText("Esportes");
        chkEsportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsportesActionPerformed(evt);
            }
        });

        lblIdioma.setText("Idioma");

        cbbIdiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inglês", "Espanhol", "Alemão", "Mandarim" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdoFeminino)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtNome)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblIdioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoMasculino)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkTecnologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAstronomia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkEsportes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoMasculino)
                    .addComponent(rdoFeminino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(chkTecnologia))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkAstronomia)
                        .addComponent(chkEsportes)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdioma)
                    .addComponent(cbbIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(rdoMasculino.isSelected()){
            sexo = "M";
            JOptionPane.showMessageDialog(null,"Sexo Selecionado: "+sexo, "Alerta!", JOptionPane.OK_OPTION);
        }
        else if (rdoFeminino.isSelected()){
            sexo = "F";
            JOptionPane.showMessageDialog(null, "Sexo Selecionado: "+sexo, "Alerta!", JOptionPane.OK_OPTION);
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo:", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
        tecnologia = chkTecnologia.isSelected();
        astronomia = chkAstronomia.isSelected();
        esportes = chkEsportes.isSelected();
        
        JOptionPane.showMessageDialog(null, "Tecnologia: "+tecnologia+"\nAstronomia: "+astronomia+"\nEsportes: "+esportes, "Alerta", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,"Idioma selecionado: " +cbbIdiomas.getSelectedItem(), "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chkTecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTecnologiaActionPerformed
        
    }//GEN-LAST:event_chkTecnologiaActionPerformed

    private void chkAstronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAstronomiaActionPerformed
        astronomia = chkAstronomia.isSelected();
    }//GEN-LAST:event_chkAstronomiaActionPerformed

    private void chkEsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsportesActionPerformed
        esportes = chkEsportes.isSelected();
    }//GEN-LAST:event_chkEsportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGrupo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbIdiomas;
    private javax.swing.JCheckBox chkAstronomia;
    private javax.swing.JCheckBox chkEsportes;
    private javax.swing.JCheckBox chkTecnologia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rdoFeminino;
    private javax.swing.JRadioButton rdoMasculino;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
